feat: Comment modal
swp2022/swp-web pull request #11
Opened 2022-05-24 14:15 UTC by min-kim-oss

해당 포스트에 댓글을 받아오는 
axios 파일에  BoardCommentGetApi, BoardCommentPostApi 추가와
mui에서 icon 사용을 위한 파일
yarn add @mui/icons-material을 설치하였습니다.

2022-05-24 15:06 UTC, sang-w0o requested changes

2022-05-24 15:06 UTC, sang-w0o commented on src/Board.js
> +      await new Promise((resolve) => setTimeout(resolve, 1000));
이건 어떤 역할을 하나요??

2022-05-24 15:06 UTC, sang-w0o commented on src/MainPage.js
> +    console.log(e);
지워주세요!

2022-05-24 15:06 UTC, sang-w0o commented on src/PostComment.js
> +    console.log(e.target.value);
지워주세요

2022-05-24 15:06 UTC, sang-w0o commented on src/util/Axios.js
> +const check =
지워주세요

2022-05-24 15:06 UTC, sang-w0o commented on src/PostComment.js
> +    BoardCommentPostApi(props.boardInfo.boardId, newComment);
이건 왜 `BoardCommentPostApi`를 await하지 않나요??

2022-05-24 15:06 UTC, sang-w0o commented on src/PostComment.js
> +  });
`useCallback()`의 2번째 인자가 지정되어 있지 않아요

2022-05-24 15:06 UTC, sang-w0o commented on src/PostComment.js
> +  });
`console.log()`는 지워주세요

2022-05-24 15:06 UTC, sang-w0o commented on src/Board.js
> +    </div>
`<div/>`로 wrapping하지 않고 `<>컴포넌트</>`로 해도 돼요!

2022-05-24 15:06 UTC, sang-w0o commented on src/Board.js
> +      await getBoards(pageNum);
`getBoards()`에서 다양한 예외가 발생할 수 있는데 예외 처리가 안되어 있네요!

2022-05-25 08:42 UTC, sang-w0o commented on src/Board.js
> +      await new Promise((resolve) => setTimeout(resolve, 1000));
이거 확인해주세요!

2022-05-30 09:04 UTC, 0chil approved these changes

2022-05-30 09:04 UTC, 0chil commented on src/Board.js
> +      await new Promise((resolve) => setTimeout(resolve, 1000));
@sang-w0o 해당 부분 다음 #13 에서 삭제되었습니다

2022-05-30 09:04 UTC, 0chil commented on src/Board.js
> +      await getBoards(pageNum);
@sang-w0o 이 부분은 다른 Pull Request에서 처리하기로 하고 다음 작업을 위해서 Merge 할까요?

2022-05-31 13:33 UTC, sang-w0o approved these changes

2022-05-31 13:33 UTC, sang-w0o commented
conflict 해결하고 merge 해주세요!

2022-05-31 13:52 UTC, merged