feat : Follower modal
swp2022/swp-web pull request #13
Opened 2022-05-30 00:45 UTC by min-kim-oss

기존의 댓글창의 ui를 변경하여 이용자의 프로필과 이름이 나올수있게 되었습니다.
follow modal의 경우 작동은 하나 어째서인지 mainpage에서 변화된 state에 따라 컴포넌트가 재생성 되지 않고 시작될시 생성된 값을 유지하는 현상을 보입니다.

2022-05-30 03:20 UTC, 0chil commented on src/PostComment.js
> +                  <Avatar alt={c.userId} src={c.profileImage} />
alt 를 쓴 이유는? 
Warning 발생하는데 체크 해보셨나요?

2022-05-30 03:20 UTC, 0chil commented on src/Board.js
> +      await new Promise((resolve) => setTimeout(resolve, 1000));
1000초를 기다리는 이유는 뭔가요?

2022-05-30 03:20 UTC, 0chil commented on src/Board.js
> +      await getBoards(pageNum);
계속 다음페이지 로드 하는 문제는
`!!getBoards.data.length`를 통해서 확인하고 observer를 제거함으로서 해결할 수 있을 것 같네요.
```javascript
const retrievedBoards = await getBoards(pageNum);
if(!!retrievedBoards.data.length)
    // observer 제거

```

2022-05-30 05:45 UTC, 0chil commented on src/PostComment.js
> +                  <Avatar alt={c.userId} src={c.profileImage} />
alt 속성 제거했습니다~

2022-05-31 13:36 UTC, sang-w0o requested changes

2022-05-31 13:36 UTC, sang-w0o commented on src/UserInfoComponent.js
> +    </>
이거 굳이 `<></>`로 안묶고 `<Box></Box>`로 하면 되지 않나요??

2022-05-31 13:36 UTC, sang-w0o commented on src/util/Axios.js
> +  "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInByb3ZpZGVyIjoidGVzdHVzZXIiLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNjUyODAxNDY4LCJleHAiOjE2NTc4ODc4Njh9.qvR3b6Alms5tAuvB7_Ryr9e3BHKFMVTY-gnnHoEiYw4nQ8EpZt
이거 매 pr 마다 리뷰 달아야 하네요. 정리 하고 올려주세요

2022-06-04 06:45 UTC, 0chil commented on src/util/Axios.js
> +  "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsInByb3ZpZGVyIjoidGVzdHVzZXIiLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNjUyODAxNDY4LCJleHAiOjE2NTc4ODc4Njh9.qvR3b6Alms5tAuvB7_Ryr9e3BHKFMVTY-gnnHoEiYw4nQ8EpZt
제거했습니다

2022-06-04 06:46 UTC, 0chil commented on src/UserInfoComponent.js
> +    </>
반영했습니다.

2022-06-04 10:17 UTC, sang-w0o reviewed
1. default export할 것이 있을 때 `Board.js`에서는 `export default function Board() { .. }`로 하고, `FollowerModal`에서는 `const FollowerModal = () => { .. }; export default FollowerModal`로 하는데, 통일하는게 좋을 것 같아요.

2022-06-04 10:17 UTC, sang-w0o commented on src/Board.js
> +      )}
isLoading이 API를 Loading하는걸 나타내는게 아니네요?! 정확히 어떤걸 loading할 때 사용하는건가요??

2022-06-04 10:17 UTC, sang-w0o commented on src/FollowerModal.js
> +    </>
`<></>` 제거

2022-06-04 10:17 UTC, sang-w0o commented on src/Board.js
> +  }, [target]);
`onIntersect`는 Dependency 추가해줘야 할 것 같아요

2022-06-04 10:17 UTC, sang-w0o commented on src/FollowerModal.js
> +  }, [setUserInfos]);
`props.search`도 dependency에 추가해줘야 하지 않나요??

2022-06-04 10:17 UTC, sang-w0o commented on src/FollowerModal.js
> +  }, []);
`getUserInfos` dependency 추가해줘야해요

2022-06-04 10:17 UTC, sang-w0o commented on src/MainPage.js
> +import { HeaderLogo, CenterWrapper, CommentBtn } from "./MainPageElements";
`CommentBtn` 안사용되네요. 여기, 그리고 MainPageElements.js에서도 제거해주세요

2022-06-04 10:17 UTC, sang-w0o commented on src/PostComment.js
> +    console.log(response);
제거해주세요

2022-06-04 10:17 UTC, sang-w0o commented on src/PostComment.js
> +    <div>
`<div>`로 묶어서 반환하는 이유가 있나요??

2022-06-05 02:03 UTC, 0chil commented on src/Board.js
> +      )}
API 로딩이 맞습니다.
`isLoadCompleted` -> 페이지의 끝에 도달했는지 (`isPagingDone` 으로 변경)
`isLoading` -> 다음 페이지 로드 중인지 (Paging)

2022-06-05 02:04 UTC, 0chil commented on src/FollowerModal.js
> +    </>
완료

2022-06-05 02:05 UTC, 0chil commented on src/Board.js
> +  }, [target]);
추가했습니다

2022-06-05 02:06 UTC, 0chil commented on src/FollowerModal.js
> +  }, [setUserInfos]);
추가했어요!

2022-06-05 02:06 UTC, 0chil commented on src/FollowerModal.js
> +  }, []);
추가했어요!

2022-06-05 02:07 UTC, 0chil commented on src/MainPage.js
> +import { HeaderLogo, CenterWrapper, CommentBtn } from "./MainPageElements";
제거했습니다

2022-06-05 02:09 UTC, 0chil commented on src/PostComment.js
> +    console.log(response);
제거했습니다

2022-06-05 02:09 UTC, 0chil commented on src/PostComment.js
> +    <div>
@min-kim-oss

2022-06-05 04:12 UTC, 0chil commented on src/PostComment.js
> +    <div>
[Pull Request #16 의 `PostComment.js` ](https://github.com/swp2022/swp-web/blob/d23fb3d6528675b43f4107b63d7314e97373578b/src/PostComment.js) 에서 
`<CommentBtn/>`을 제거하면서 해결되는 내용입니다.

2022-06-05 14:36 UTC, sang-w0o commented on src/Board.js
> +  };
저한테는 아래와 같은 eslint warning이 나타나네요.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/48438083/172055779-22d18d8e-3e2b-48be-abbf-3adf52cc5c15.png">


아래와 같이 바꿔야하는거 아닐까요??

```js
const [pageNum, setPageNum] = useState(0);
  const onIntersect = useCallback(
    async ([entry], observer) => {
      if (entry.isIntersecting && !isLoading) {
        observer.unobserve(entry.target);
        setIsLoading(true);

        const retrivedCount = await getBoards(pageNum);
        if (!retrivedCount) setIsPagingDone(true);
        setPageNum(pageNum + 1);

        setIsLoading(false);
        observer.observe(entry.target);
      }
    },
    [pageNum, getBoards, isLoading],
  );
```

2022-06-05 14:36 UTC, sang-w0o commented on src/Board.js
> +  };
참고로 제 스크린샷은 eslint vscode plugin을 설치하면 나타나요 ㅎㅎ

2022-06-05 15:58 UTC, 0chil commented on src/Board.js
> +  };
문제가 지속적으로 발생하여 reducer를 제거하고 state로 처리하였습니다.(해결)
로직 상의 차이는 없습니다.
그리고 `util`에 `InfiniteScroll.js`을 별도로 뺐습니다.

```javascript
import { useEffect, useState } from "react";

export const InfiniteScroll = ({
  root = null,
  threshold = 0.4,
  rootMargin = "0px",
  onIntersect,
}) => {
  const [target, setTarget] = useState(null);

  useEffect(() => {
    let observer;
    if (target) {
      observer = new IntersectionObserver(onIntersect, {
        root,
        rootMargin,
        threshold,
      });
      observer.observe(target);
    }
    return () => observer && observer.disconnect();
  }, [onIntersect, root, rootMargin, target, threshold]);
  return [setTarget];
};

```

2022-06-06 10:33 UTC, merged