feat: 로그아웃, localStorage
swp2022/swp-web pull request #3
Opened 2022-05-18 08:58 UTC by min-kim-oss

로그아웃 기능과 redux init state를 local storage로 초기화하는 부분입니다.

2022-05-18 09:18 UTC, sang-w0o requested changes

2022-05-18 09:18 UTC, sang-w0o commented on src/util/storage.js
> +    localStorage.clear();
앞으로 localStorage에 어떤 정보를 담을지 몰라서, `clear()` 보다는 명시적으로 `removeItem()`을 해주는게 좋을 것 같아요!

2022-05-18 09:18 UTC, sang-w0o commented on src/UserSectionElements.js
> +    border-radius: 10px;
tab이 4칸이네요! 기본 2칸 아닌가요??

2022-05-18 09:18 UTC, sang-w0o commented on src/MainPageElements.js
> +  right:0;
`right: 0;`

2022-05-18 09:18 UTC, sang-w0o commented on src/MainPageElements.js
> +  bottom : 0;
`bottom: 0;`

2022-05-18 09:18 UTC, sang-w0o commented on src/UserSectionElements.js
> +    margin 20px auto;
이거 잘못된 문법 아닌가요?

2022-05-18 09:18 UTC, sang-w0o commented on src/UserSectionElements.js
> +  color : #d3d3d3;
`color: #d3d3d3`

2022-05-18 09:18 UTC, sang-w0o commented on src/UserSectionElements.js
> +  right:0;
`right: 0;`

2022-05-18 09:18 UTC, sang-w0o commented on src/MainPageElements.js
> +export const SecrchBar = styled.input`
변수명 오타 난 것 같아요

2022-05-18 09:18 UTC, sang-w0o commented on src/MainPage.js
> +  }
arrow function으로 통일하는거 어때요?
아래 `checkLogout()`도 포함

2022-05-18 09:18 UTC, sang-w0o commented on src/MainPage.js
> +  }
+ 아래에 `storage.js`에 `clearStorage()` 함수 있는데, 왜 `window.localStorage.clear()`를 명시적을 호출하셨나요??

2022-05-18 10:07 UTC, 0chil commented on src/MainPage.js
> +  }
@sang-w0o storage.js 를 제가 작성해서 있는지 몰랐나 봅니다
@min-kim-oss storage.js 임포트 하셔서 clearStorage() 하시면 됩니다.

2022-05-19 10:07 UTC, sang-w0o commented on src/MainPageElements.js
> +
불필요한 공백이네요

2022-05-20 08:16 UTC, merged